"""followers

Revision ID: 2344ef299dee
Revises: 8024616a5f10
Create Date: 2023-08-06 20:15:26.260320

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2344ef299dee'
down_revision = '8024616a5f10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
